"""
Presenter Agent - Produces final structured output
"""
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage
from datetime import datetime


class PresenterAgent:
    """Agent responsible for creating final structured presentation"""

    def __init__(self, api_key: str, model_name: str = "gemini-3.6-flash"):
        """Initialize the Presenter Agent with Gemini model"""
        self.llm = ChatGoogleGenerativeAI(model=model_name, google_api_key=api_key)
        self.model_name = model_name
        self.name = "Presenter Agent"

    def create_presentation(self, refined_data: dict) -> dict:
        """
        Create a final structured presentation of the creative process and results

        Args:
            refined_data: Dictionary containing refined ideas from the Refiner Agent

        Returns:
            dict: Contains the final structured presentation
        """
        topic = refined_data.get("topic", "Unknown")
        original_ideas = refined_data.get("original_ideas", "")
        critique = refined_data.get("critique", "")
        refined_ideas = refined_data.get("refined_ideas", "")

        prompt = f"""You are a Presenter Agent. Create a professional, executive-ready presentation document that showcases the entire creative process and final recommendations.

TOPIC: {topic}

ORIGINAL IDEAS:
{original_ideas}

CRITICAL ANALYSIS:
{critique}

REFINED IDEAS:
{refined_ideas}

Create a comprehensive presentation document with:

1. EXECUTIVE SUMMARY
   - Brief overview of the project
   - Key findings and recommendations

2. CREATIVE PROCESS OVERVIEW
   - How ideas were generated
   - How they were critiqued
   - How they were refined

3. FINAL RECOMMENDATIONS (Top 3 Ideas)
   - Present each refined idea with:
     * Title
     * Complete description
     * Target audience
     * Implementation roadmap
     * Expected outcomes
     * Risk mitigation strategies

4. COMPARISON ANALYSIS
   - How original ideas evolved
   - Key improvements made
   - Value added through the refinement process

5. NEXT STEPS
   - Action items
   - Timeline suggestions
   - Resource requirements

Make it professional, clear, and actionable. Use markdown formatting for better readability."""

        response = self.llm.invoke([HumanMessage(content=prompt)])
        presentation_text = self._to_text(response.content)

        return {
            "agent": self.name,
            "topic": topic,
            "presentation": presentation_text,
            "generated_at": datetime.now().isoformat(),
            "status": "completed"
        }

    def save_presentation(self, presentation_data: dict, filename: str = None):
        """
        Save the presentation to a markdown file

        Args:
            presentation_data: The presentation data to save
            filename: Optional filename (default: creative_studio_output_[timestamp].md)
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"creative_studio_output_{timestamp}.md"

        content = f"""# Multi-Agent Creative Studio Output

**Topic:** {presentation_data.get('topic', 'Unknown')}
**Generated:** {presentation_data.get('generated_at', 'Unknown')}
**Agent:** {presentation_data.get('agent', 'Unknown')}

---

{presentation_data.get('presentation', '')}

---

*Generated by Multi-Agent Creative Studio*
*Powered by Google Gemini 3.6 Flash*
"""

        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)

        return filename

    def _to_text(self, content) -> str:
        """Normalizes LangChain response content to a plain string.
        Gemini via langchain-google-genai sometimes returns a list of
        content blocks instead of a plain string."""
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            parts = []
            for block in content:
                if isinstance(block, str):
                    parts.append(block)
                elif isinstance(block, dict):
                    parts.append(block.get("text", ""))
            return "\n".join(parts)
        return str(content)

    def __str__(self):
        return f"{self.name} (Gemini-powered presentation creator)"