"""
Presenter Agent - Produces final structured output
"""
from google import genai
from google.genai import types
import json
from datetime import datetime


class PresenterAgent:
    """Agent responsible for creating final structured presentation"""
    
    def __init__(self, api_key: str, model_name: str = "gemini-3.6-flash"):
        """Initialize the Presenter Agent with Gemini model"""
        self.client = genai.Client(api_key=api_key)
        self.model_name = model_name
        self.name = "Presenter Agent"
    
    def create_presentation(self, refined_data: dict) -> dict:
        """
        Create a final structured presentation of the creative process and results
        
        Args:
            refined_data: Dictionary containing refined ideas from the Refiner Agent
            
        Returns:
            dict: Contains the final structured presentation
        """
        topic = refined_data.get("topic", "Unknown")
        original_ideas = refined_data.get("original_ideas", "")
        critique = refined_data.get("critique", "")
        refined_ideas = refined_data.get("refined_ideas", "")
        
        prompt = f"""You are a Presenter Agent. Create a professional, executive-ready presentation document that showcases the entire creative process and final recommendations.

TOPIC: {topic}

ORIGINAL IDEAS:
{original_ideas}

CRITICAL ANALYSIS:
{critique}

REFINED IDEAS:
{refined_ideas}

Create a comprehensive presentation document with:

1. EXECUTIVE SUMMARY
   - Brief overview of the project
   - Key findings and recommendations

2. CREATIVE PROCESS OVERVIEW
   - How ideas were generated
   - How they were critiqued
   - How they were refined

3. FINAL RECOMMENDATIONS (Top 3 Ideas)
   - Present each refined idea with:
     * Title
     * Complete description
     * Target audience
     * Implementation roadmap
     * Expected outcomes
     * Risk mitigation strategies

4. COMPARISON ANALYSIS
   - How original ideas evolved
   - Key improvements made
   - Value added through the refinement process

5. NEXT STEPS
   - Action items
   - Timeline suggestions
   - Resource requirements

Make it professional, clear, and actionable. Use markdown formatting for better readability."""
        
        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt
        )
        presentation_text = response.text
        
        return {
            "agent": self.name,
            "topic": topic,
            "presentation": presentation_text,
            "generated_at": datetime.now().isoformat(),
            "status": "completed"
        }
    
    def save_presentation(self, presentation_data: dict, filename: str = None):
        """
        Save the presentation to a markdown file
        
        Args:
            presentation_data: The presentation data to save
            filename: Optional filename (default: creative_studio_output_[timestamp].md)
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"creative_studio_output_{timestamp}.md"
        
        content = f"""# Multi-Agent Creative Studio Output

**Topic:** {presentation_data.get('topic', 'Unknown')}
**Generated:** {presentation_data.get('generated_at', 'Unknown')}
**Agent:** {presentation_data.get('agent', 'Unknown')}

---

{presentation_data.get('presentation', '')}

---

*Generated by Multi-Agent Creative Studio*
*Powered by Google Gemini 2.5 Flash*
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return filename
    
    def __str__(self):
        return f"{self.name} (Gemini-powered presentation creator)"
